### ISSUE TITLE
'opennsfw2' has no attribute 'preprocess_image' 

### ISSUE THREAD

**Issue by shuangmei** [bhky/opennsfw2#1]
partially initialized module 'opennsfw2' has no attribute 'preprocess_image' (most likely due to a circular import)
这是什么原因啊

**Comment by bhky** [comment]
Hello! Thanks for the question.

I think you may have another local file with the same name. Please take a look at the following thread. Hope it helps! :slightly_smiling_face: 
https://stackoverflow.com/questions/59762996/how-to-fix-attributeerror-partially-initialized-module
