### ISSUE TITLE
OpenNSFW in PyTorch

### ISSUE THREAD

**Issue by Momilijaz96** [bhky/opennsfw2#13]
Hey!
Thanks for great work!
Your current work is using tensorflow and the highest supported CUDA driver version for TF gpu usage is 11.8
I am running CUDA 12.2, and cannot get to use ur code with gpu, as tf does not supports gpu for cuda above 11.8
Do u have any valuable resoruce to convert/ckpts this work in pytorch?

**Comment by bhky** [comment]
Hello! Thank you for your interest in the library!

Currently we don't have a plan to make a PyTorch implementation. However, we do plan to switch from `tf.keras` to [Keras Core](https://keras.io/keras_core/announcement/), which will support PyTorch backend, at least in principle.

We have done some experiments and found that with Keras Core the model could run on PyTorch, BUT the inference results were "quite different" comparing with using TensorFlow or JAX. We are still unsure why, maybe it's on Keras Core, after all it's still a Beta release.

Therefore at the moment I am afraid we still can't use PyTorch with this model, but I think Keras Core will make it possible in its stable release in the future.

**Comment by Momilijaz96** [comment]
Sure thanks for the response.
