### ISSUE TITLE
How to continue train the model?

### ISSUE THREAD

**Issue by lukywangwang** [bhky/opennsfw2#14]
I have my own porn dataset. How can I resume the training process with the the current model?
thanks 
Best.

**Comment by bhky** [comment]
Hi! Thanks for the message.

The model object is a normal [Keras model](https://keras.io/api/models/model/). You can follow [this section](https://github.com/bhky/opennsfw2#lower-level-with-keras-core) on how to do the data preprocessing and instantiate the model. Then you can just use the standard way of training a TensorFlow/Keras model with your dataset.

If you are new to using TensorFlow/Keras, you can take a look at [this guide](https://keras.io/getting_started/intro_to_keras_for_engineers/).
