### ISSUE TITLE
Replace PIL with CV2

### ISSUE THREAD

**Issue by henryruhs** [bhky/opennsfw2#16]
At this time I might "piss you off" by asking to replace Pillow by OpenCV and Numpy? Most AI projects have this dependencies already so it makes sense to me - in our case I have the PIL dependency just for one line:

```
image = Image.fromarray(target_frame)
```

It's fine you close that issue instantly. Please consider it.

**Comment by bhky** [comment]
Hi! Thanks for the suggestion, and no you are not pissing anyone off. :)

I personally have no special preference toward OpenCV or PIL in this regard, however, the original intention of this library was to reproduce as close as possible the steps used in the discontinued Yahoo project, to avoid any surprises. The way to load and preprocess images with PIL was migrated from there. In addition, PIL is still the choice for TF/Keras in their [image loading utility](https://www.tensorflow.org/api_docs/python/tf/keras/utils/load_img). Therefore currently I do not plan to change this.
