### ISSUE TITLE
Huge video memory footprint

### ISSUE THREAD

**Issue by MisakaMikoto-o** [bhky/opennsfw2#20]
My python version is 3.8, cuda version is 10.2.

**Comment by MisakaMikoto-o** [comment]
I have sovled it with upgrading my cuda version to 11.4

**Comment by MisakaMikoto-o** [comment]
but the model is so large that it takes up almost all of my 16 gigabytes of video memory,  while the h5 model file is just 23MB

**Comment by bhky** [comment]
Hello! Thanks for your interest in the library!
I'm glad that you have figured out the CUDA issue. :+1: 

On the model size..... I'm sorry that I also don't have a solution for it.

For the **model object** itself, you may try to convert it to a TF Lite object as described [here](https://www.tensorflow.org/lite/performance/post_training_float16_quant), but I have never tried it. :thinking: 

Also, this is only for the model object, so you probably need some fiddling with the preprocessing steps on your own as shown [here](https://github.com/bhky/opennsfw2#lower-level-with-keras-core).
