### ISSUE TITLE
sample output

### ISSUE THREAD

**Issue by NasaKHw** [bhky/opennsfw2#23]
hello,
thanks for ur great work
can we get an example output of video processing ? like is it able to detect hentai or anime nudity too ?

**Comment by bhky** [comment]
Hello! Thanks for your interest in the library!

We don't have a particular example for NSFW videos. However, YAHOO gives the following [description](https://github.com/yahoo/open_nsfw?tab=readme-ov-file#not-suitable-for-work-classifier) to the model:
```
Defining NSFW material is subjective and the task of identifying these images is non-trivial. Moreover, what may be objectionable in one context can be suitable in another. For this reason, the model we describe below focuses only on one type of NSFW content: pornographic images. The identification of NSFW sketches, cartoons, text, images of graphic violence, or other types of unsuitable content is not addressed with this model.
```
Therefore, it is expected that the performance on hentai or anime would not be too good.
