### ISSUE TITLE
Which NSFW Area is this AI covering?

### ISSUE THREAD

**Issue by Flori00123** [bhky/opennsfw2#4]
Hi,

very cool project, I am looking for an AI, which can cover on the one side nudity, but doesn't judge sexy images and also bans traumatic images, like horror and the crazy things, like NSFW 4 things, is it possible with this AI?

![nsfw-chart](https://user-images.githubusercontent.com/89021114/150615051-9a6a56a4-4714-4e96-aa46-9e4682012487.jpg)

I found this image online, which is your AI covering?

Thanks!

**Comment by bhky** [comment]
Hi! Thanks for the message. This implementation uses the weights trained in the [Yahoo Open-NSFW project](https://github.com/yahoo/open_nsfw), which targets at pornographic content. For the scheme that you are proposing, it probably means area 2.

**Comment by Flori00123** [comment]
Would it be possible to add Nsfw 4 too? I am not into Tensorflow but i am looking for a moderation system, which also would detect like images from horror, dead, ect. Like all those things you not wanna see.

**Comment by bhky** [comment]
Unfortunately this is out of the scope for this project. :)

**Comment by Flori00123** [comment]
Ok, whats the scope of the project? Would it be via forking the project to reach this?

**Comment by bhky** [comment]
Please refer to the [introduction](https://github.com/bhky/opennsfw2#introduction) of this project.
I think what you want to achieve is very different from what is provided here. The first thing you need to consider is whether you have the required data to train your model, and then you could try out different methods. I am afraid this project may not be so helpful for you.
