### ISSUE TITLE
module 'opennsfw2' has no attribute 'predict_images'

### ISSUE THREAD

**Issue by yasersakkaf** [bhky/opennsfw2#6]
Please help resolve this error for python3.6

`module 'opennsfw2' has no attribute 'predict_images'`

**Comment by bhky** [comment]
Hello! Thank you for your interest in the library. Unfortunately, as mentioned in the [installation instructions](https://github.com/bhky/opennsfw2#installation), we only support Python 3.8, 3.9, and 3.10, because of other library dependencies.

**Comment by yasersakkaf** [comment]
Thanks, but i got the solution to this issue.

It's to use the part **Lower level with TensorFlow / Keras**
https://github.com/bhky/opennsfw2#lower-level-with-tensorflow--keras

**Comment by bhky** [comment]
That is awesome! Thanks for the report!
