### ISSUE TITLE
Support for Mac M1

### ISSUE THREAD

**Issue by henryruhs** [bhky/opennsfw2#9]
This awesome lib depends on `tensorflow` and therefore cannot be installed on Mac with M1 chip as this needs `tensorflow-macos`. We are using [opennsfw2](https://github.com/bhky/opennsfw2) for [roop](https://github.com/s0md3v/roop) and would love to give support to our users.

**Comment by henryruhs** [comment]
Nevermind, they fixed it via tensorflow==2.13.0rc1

**Comment by bhky** [comment]
Hello! Thank you for your comment and your interest in the library!
I totally agree that M1 is still quite troublesome, and I am glad that you have found a way that works!

**Comment by henryruhs** [comment]
Thanks for your work.
